--

DROP SEQUENCE sequenceSeg;
DROP SEQUENCE sequenceSalle;
DROP SEQUENCE sequencePoste;
DROP SEQUENCE sequenceLog;
DROP SEQUENCE sequenceTyp;
DROP SEQUENCE sequenceIns;


CREATE SEQUENCE sequenceSeg
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 10000
  NOCYCLE;
  
CREATE SEQUENCE sequenceSalle
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 10000
  NOCYCLE;

CREATE SEQUENCE sequencePoste
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 10000
  NOCYCLE;
  
CREATE SEQUENCE sequenceLog
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 10000
  NOCYCLE;
  
CREATE SEQUENCE sequenceTyp
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 10000
  NOCYCLE;

CREATE SEQUENCE sequenceIns
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 10000
  NOCYCLE;
  
COMMIT;
